---
title: "Practica2"
author: "Luis Torres"
date: "18/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(htmltab)
link1= "https://www.cia.gov/library/publications/resources/the-world-factbook/fields/343.html"
path='//*[@id="fieldListing"]'
dataCIA= htmltab(doc = link1, which =path)
```
1)  #Existen 230 observaciones y 2 columnas

```{r}
str(dataCIA)
```
# segun el STR ambas columas son caracteres, pero a primera vista podemos ver que son tanto texto como valores numericos 

2) se usa el str_split y el parse_number
```{r}
library(stringr)
library(readr)
dataCIA$promedio=str_split(string = dataCIA$`Median age`,
                         pattern = ' ',
                         simplify = T)[,1]
dataCIA$promedio = parse_number(dataCIA$promedio)
```


```{r}
str(dataCIA$promedio)
```
3) Max valor 55.4 Min valor 14.8 Promedio 31.54652

```{r}
max(dataCIA$promedio)
```
```{r}
min(dataCIA$promedio)
```
```{r}
mean(dataCIA$promedio)
```






